### ISSUE TITLE
Create cpp file if now exists

### ISSUE THREAD

**Issue by navarrothiago** [amir9480/vscode-cpp-helper#14]
It would be good when you click on `Create Implementation`, if the `.cpp` file does not exist, it should create a new `.cpp` file with the same name of the `.hpp`.

**Comment by amir9480** [comment]
Hello,

Personally, I prefer to create the implementation in the same header file if source file not found instead of creating a new one.
So I provided this as an option.
You can enable it via "CppHelper.SourceNotFoundBehavior" setting:
```json
{
    "CppHelper.SourceNotFoundBehavior": "Create source file"
}
```

It will be available in the next version.

https://github.com/amir9480/vscode-cpp-helper/commit/b53672f7cb6b341d3e9f6dbadbcd9d6f2e0a46b6
