### ISSUE TITLE
not creating implementation in .cpp correctly

### ISSUE THREAD

**Issue by BazzalSeed** [amir9480/vscode-cpp-helper#15]
My file layout is simply like this
<img width="198" alt="Screen Shot 2020-06-19 at 5 27 34 PM" src="https://user-images.githubusercontent.com/14510588/85180745-2b324a80-b252-11ea-97c3-dfcbbf7997af.png">

I changed the settings to this
<img width="738" alt="Screen Shot 2020-06-19 at 5 28 14 PM" src="https://user-images.githubusercontent.com/14510588/85180783-43a26500-b252-11ea-8e0c-d0ba6b566cb5.png">

You can see, even though i click on `create implementation`. It's creating all the implementations in place in stead of in .cpp. 

![bug_impl](https://user-images.githubusercontent.com/14510588/85180878-8cf2b480-b252-11ea-812e-ae12a757fbb2.gif)
Would appreciate your help

**Comment by amir9480** [comment]
Hello @BazzalSeed 

I'm not sure why this happening but I noticed you have an error in your JSON config.
```json
[
...
"{FILE}.c",
]
```
You should remove the last comma in your array.
Fix it and if still issue exists please let me know.

**Comment by louis123456** [comment]
I have the same issue, it seems to be happening when class is in a namespace

**Comment by dstodev** [comment]
I'm having this same issue.

It seems like this happens when:
- If `"CppHelper.SourceNotFoundBehavior": "Create source file",` is set
- The .cpp file for the class already exists

So, to test, I made this header:
```
#ifndef CLASS_H
#define CLASS_H

class Test
{
public:
	void func1();
	void func2();
};

#endif  // CLASS_H
```

Using "Create Implementation" works for func1, but then creating the implementation for func2 afterwards will put it in the header file instead of the .cpp file.

**Comment by amir9480** [comment]
@dstodev 
Your information helped me a lot. Thank you.


@louis123456 @BazzalSeed 

Please update to v0.2.2.
