### ISSUE TITLE
Create implementation doesn't work (0.0.6)

### ISSUE THREAD

**Issue by SergeyFi** [amir9480/vscode-cpp-helper#5]
Hi, cool extension but on version 0.0.6 "Create implementation" doesn't work.
On version 0.0.5 everything works fine.
What information do I need to provide so that you can fix the bug?

VSCode version: 1.43.2
OS:Windows 10 x64.

**Comment by amir9480** [comment]
Hello.
Thanks for using C++ Helper.

First, check if you can see `Function not detected.` message when you click "Create implementation". If you see that then please send a sample header code that does not work.

Otherwise, please follow these instructions to check error.

**Comment by SergeyFi** [comment]
Hi. I followed the instructions and here is the result: 

[8667.log](https://github.com/amir9480/vscode-cpp-helper/files/4431068/8667.log)
[exthost-c85225.cpuprofile.txt](https://github.com/amir9480/vscode-cpp-helper/files/4431070/exthost-c85225.cpuprofile.txt)

P.S I noticed that the implementation was eventually created, but with a big lag.

**Comment by amir9480** [comment]
So I tested your code and figured out this happening because of Unreal Engine macros like ( UCLASS, GENERATED_BODY, ... ) causing the problem because of no ";" at end of statement so regex takes too much time to parse.

I optimized regex based on your code and now it look like working.
Please update to version 0.0.7 and if still any issue exists let me know.
